#!/u/y01146/miniconda/envs/sandbox/bin/bash

if [ $FROM_ISPF = 1 ];then
    exit 0
fi
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
CCNO=$(echo "$BRANCH_NAME" | cut -c2-11 | sed 's/^0*//')

if echo "$CCNO" | grep -qE '^[0-9]+$'; then
    export STEPLIB=PRD.Y01137.ISPF.ISPLLIB
    RES=$(tsocmd exec "'PRD.Y01137.REXXLIB(CCSTEXT)'" "'$CCNO'")
    read rcode stat ccown desc<<< "$RES"
    if [ "$rcode" = 0 ]; then
        echo "$BRANCH_NAME - $desc" > "$1"
    fi
fi

exit 0

