name: Pre-Receive Validation

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-push:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required so 'git diff' can see both branches

      - name: Extract CC Number from Commit Message
        shell: 'C:\Program Files\Git\bin\bash.exe'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B ${{ github.event.pull_request.head.sha }})
          
          CC_NO=$(echo "$COMMIT_MSG" | cut -c2-11 | sed 's/^0*//' | tr -d ' ')
          
          if ! echo "$CC_NO" | grep -qE '^[0-9]+$'; then
             echo "Error: The commit message must start with a numeric CC Number."
             echo "Found: $COMMIT_MSG"
             exit 1
          fi
          
          echo "CC_NUMBER=$CC_NO" >> $GITHUB_ENV

      - name: Run Validation Script
        shell: 'C:\Program Files\Git\bin\bash.exe'
        env:
          MF_PASSWORD: ${{ secrets.ZOSMF_PASSWORD }}
        run: |
          chmod +x ./hooks/validate_pr.sh ./hooks/owner_check
          ./hooks/validate_pr.sh ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} ${{ env.CC_NUMBER }}		  
